version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" 
    schedule:
      interval: "daily"
    groups:
      security-updates:
        applies-to: security-updates
        group-name: "all-security-updates"
